minimumReleaseAge: 10080
minimumReleaseAgeIgnoreMissingTime: false
trustLockfile: false
strictDepBuilds: true
allowBuilds:
  esbuild: true
  fsevents: true
storeDir: .pnpm-store
cacheDir: .pnpm-store/policy-cache
enableGlobalVirtualStore: false
packageImportMethod: clone-or-copy
