'use client';
import {useEffect,useRef,useState} from 'react';
import {Bug,Download,Heart,Info,Pause,Play,SkipForward,X} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogTrigger} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Progress} from '@/components/ui/progress';
import {FlyScene,BrainScene} from '@/components/experiment/scene';
import {assetPath} from '@/lib/asset-path';
import {useFly,type Swipe,type Tick,type Meta,type Evaluation} from '@/hooks/use-fly';
const num=(n:number)=>Intl.NumberFormat('en-US').format(n);
const pct=(n:number)=>`${Math.round(n*100)}%`;
function BrainView({meta,tick}:{meta?:Meta;tick?:Tick}){
 const ref=useRef<HTMLCanvasElement>(null);
 useEffect(()=>{const canvas=ref.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;
  const draw=()=>{const {width,height}=canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,width,height);if(!meta)return;
   meta.points.forEach((p,k)=>{const x=width*.08+p[1]*width*.84,y=height*.04+p[2]*height*.9;const fired=(tick?.activity[k]||0)>0;ctx.fillStyle=fired?'rgba(188,247,123,.95)':'rgba(149,167,161,.19)';ctx.beginPath();ctx.arc(x,y,fired?1.9:.9,0,Math.PI*2);ctx.fill();});
  };draw();const observer=new ResizeObserver(draw);observer.observe(canvas);return()=>observer.disconnect();
 },[meta,tick]);
 return <canvas ref={ref} className="brain-canvas" aria-label="Fly neurons: green points fired during the latest simulation step"/>;
}
function Retina({pixels}:{pixels:number[]}){
 const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const ctx=ref.current?.getContext('2d');if(!ctx||!pixels.length)return;const im=ctx.createImageData(32,32);pixels.forEach((v,i)=>{im.data[4*i]=im.data[4*i+1]=im.data[4*i+2]=Math.round(v*255);im.data[4*i+3]=255;});ctx.putImageData(im,0,0);},[pixels]);
 return <canvas ref={ref} width={32} height={32} className="retina" aria-label="Grayscale portrait input to the fly"/>;
}
function SignalChart({trace}:{trace:Tick[]}){
 const max=Math.max(1,...trace.map(t=>t.spikes));const points=trace.map((t,i)=>`${i/69*600},${65-t.spikes/max*50}`).join(' ');
 return <svg viewBox="0 0 600 78" preserveAspectRatio="none" className="signal-chart" role="img" aria-label="Recent neural spike activity"><path d="M0 20H600M0 43H600M0 66H600" stroke="#26312d" strokeDasharray="3 6" fill="none"/><polyline points={points} fill="none" stroke="#bcf77b" strokeWidth="1.8" vectorEffect="non-scaling-stroke"/></svg>;
}
function SourceDownload(){const [progress,setProgress]=useState<number|null>(null),[error,setError]=useState('');async function download(){setError('');setProgress(0);try{const {downloadSource}=await import('@/lib/download-source');await downloadSource(setProgress);}catch(e){setError(e instanceof Error?e.message:'Download failed');}finally{setProgress(null);}}return <div><button className="text-button" onClick={download} disabled={progress!==null}><Download size={16}/>{progress!==null?`Downloading ${progress}%`:'Download source'}</button>{error&&<p role="alert">{error}</p>}</div>;}
function Methods({evaluation:e}:{evaluation?:Evaluation}){return <Dialog><DialogTrigger asChild><button className="icon-button" aria-label="Training results and how it works"><Info size={20}/></button></DialogTrigger><DialogContent className="method-dialog"><DialogHeader><DialogTitle>What learned?</DialogTitle><DialogDescription>A trained readout of a simulated fly brain.</DialogDescription></DialogHeader><div className="method-body"><p>Portrait → grayscale retina → 166,700 simulated neurons → learned like/pass readout. The connectome stays fixed. The readout was trained offline on human ratings; this page evaluates frozen weights.</p>{e?<><div className="result-grid"><div><strong>{pct(e.neural.accuracy)}</strong><span>held-out accuracy</span></div><div><strong>{pct(e.alwaysLike.accuracy)}</strong><span>always-like baseline</span></div></div><p>{e.train} training portraits · {e.validation} validation · {e.test} test. Correct on {e.neural.correct}/{e.neural.total} test portraits; 95% interval {e.neural.accuracy95CI.map(pct).join('–')}.</p><p>Image-only baseline: {pct(e.comparisons['pixels-8x8'].accuracy)}. Shuffled training labels: {pct(e.shuffledLabels.meanAccuracy)} average. These are measured offline results, not a live accuracy counter.</p></>:<p>Results load with the brain.</p>}<p>SCUT-FBP5500 portraits from its adult-source subset, using the higher and lower rating thirds. This small, narrow sample reflects those raters’ preferences; it does not establish general attractiveness recognition.</p><p>Each portrait starts from the same warmed-up state, then runs for 200 ms of brain time. Green points show actual spikes at sampled measured 3D neuron positions. The fly avatar and body movements illustrate the decision; they are not a muscle or behavior simulation. The score is the readout’s like output, not a calibrated attractiveness rating.</p><p>All displayed portraits were withheld from training and model selection. The sequence repeats. No real Tinder account is connected. History is saved in this browser.</p><div className="source-links"><a href={assetPath('/brain/readout.json')} target="_blank" rel="noreferrer">Model & results ↗</a><a href="https://github.com/HCIILAB/SCUT-FBP5500-Database-Release" target="_blank" rel="noreferrer">Dataset ↗</a><a href="https://github.com/nftechie/doomfly" target="_blank" rel="noreferrer">Simulator ↗</a></div><p className="muted">Dataset: non-commercial research use only. Full methods, limitations, and reproduction scripts are included with the source.</p><SourceDownload/></div></DialogContent></Dialog>;}
function SwipeDetail({swipe:s}:{swipe:Swipe}){return <Dialog><DialogTrigger asChild><button className="history-card" aria-label={`Inspect ${s.profile.name}: ${s.decision}`}><img src={assetPath(s.profile.image)} alt=""/><span className={`history-decision ${s.decision}`}>{s.decision==='like'?<Heart size={14}/>:s.decision==='pass'?<X size={14}/>:<Pause size={14}/>} {s.decision==='like'?'Like':s.decision==='pass'?'Pass':'Hold'}</span><span className="history-name">{s.profile.name}</span></button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>{s.profile.name} · {s.decision==='like'?'Like':s.decision==='pass'?'Pass':'Hold'}</DialogTitle><DialogDescription>{new Date(s.at).toLocaleString()}</DialogDescription></DialogHeader><div className="decision-detail"><img src={assetPath(s.profile.image)} alt={s.profile.name}/><dl>{s.score!==undefined&&<><dt>Like score</dt><dd>{pct(s.score)}</dd></>}<dt>Neural spikes</dt><dd>{num(s.totalSpikes)}</dd><dt>Brain time</dt><dd>{s.brainMs} ms</dd><dt>Compute time</dt><dd>{(s.computeMs/1000).toFixed(2)} s</dd><dt>Model</dt><dd>{s.modelVersion||'Original fixed decoder'}</dd></dl></div></DialogContent></Dialog>;}
function History({items}:{items:Swipe[]}){
 const [filter,setFilter]=useState('all'),[limit,setLimit]=useState(14);const filtered=items.filter(s=>filter==='all'||s.decision===filter);
 function download(){const url=URL.createObjectURL(new Blob([JSON.stringify(items,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='fly-swipe-history.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <section className="history-section"><div className="section-heading"><h2>Swipe history <span>{num(items.length)}</span></h2><div className="history-actions"><Select value={filter} onValueChange={v=>{setFilter(v);setLimit(14);}}><SelectTrigger aria-label="Filter swipe history"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All</SelectItem><SelectItem value="like">Likes</SelectItem><SelectItem value="pass">Passes</SelectItem><SelectItem value="hold">Holds</SelectItem></SelectContent></Select><button className="icon-button" disabled={!items.length} onClick={download} aria-label="Export swipe history"><Download size={17}/></button></div></div>{filtered.length?<><div className="history-grid">{filtered.slice(0,limit).map(s=><SwipeDetail key={s.id} swipe={s}/>)}</div>{filtered.length>limit&&<button className="text-button show-more" onClick={()=>setLimit(n=>n+28)}>Show more</button>}</>:<p className="empty-history">{items.length?'No matching swipes.':'The first swipe will appear here.'}</p>}</section>;
}
export default function Home(){
 const fly=useFly(),loading=fly.status==='loading';
 return <main className="app-shell"><header className="topbar"><a href={assetPath('/')} className="brand"><Bug size={26}/> flyswipe</a><div className="top-actions"><span className="run-status">{loading?'Loading':fly.status==='error'?'Stopped':fly.running?'Live':'Paused'}</span><button className="control-button" disabled={fly.status!=='ready'} onClick={fly.toggle}>{fly.running?<Pause size={17}/>:<Play size={17}/>}<span>{fly.running?'Pause':'Resume'}</span></button><button className="icon-button" disabled={fly.status!=='ready'} onClick={fly.single} aria-label="Run one portrait, then pause"><SkipForward size={19}/></button><Select value={fly.speed} onValueChange={fly.changeSpeed}><SelectTrigger className="speed-select" aria-label="Playback pace"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="0.5">0.5×</SelectItem><SelectItem value="1">1×</SelectItem><SelectItem value="2">2×</SelectItem><SelectItem value="4">4×</SelectItem></SelectContent></Select><Methods evaluation={fly.evaluation}/></div></header>
 <div className="experiment-grid"><section className="portrait-panel"><div className="world-stage"><div className="world-heading"><span>FLY VIEW</span><span>{fly.profile.name}</span></div><FlyScene state={{image:assetPath(fly.profile.image),decision:fly.decision?.decision,running:fly.running&&fly.status==='ready'}} fallback={<img className="profile-photo" src={assetPath(fly.profile.image)} alt={fly.profile.name}/>}/></div><div className="decision-row" aria-live="polite"><span className={`decision-icon ${fly.decision?.decision||''}`}>{fly.decision?.decision==='like'?<Heart size={24}/>:fly.decision?.decision==='pass'?<X size={24}/>:<Bug size={24}/>}</span><div><h1>{loading?'Loading brain…':fly.status==='error'?'Simulation stopped':fly.decision?fly.decision.decision==='like'?'Like':'Pass':fly.running?'Looking…':'Paused'}</h1><span className="muted">{fly.decision?.score!==undefined?`${pct(fly.decision.score)} like score`:`${fly.windowMs} / 200 ms brain time`}</span></div><span className="portrait-counter">{fly.index+1}</span></div><Progress value={fly.windowMs/2} className="exposure-progress"/></section>
 <section className="brain-panel"><div className="section-heading"><h2>Brain activity</h2><span className="muted">166,700 neurons</span></div><div className="brain-area"><BrainScene meta={fly.meta} tick={fly.tick} fallback={<BrainView meta={fly.meta} tick={fly.tick}/>}/>{loading&&<div className="brain-overlay"><Bug size={30}/><strong>{fly.progress===100?'Warming up…':`Loading ${fly.progress}%`}</strong><Progress value={fly.progress}/><span className="muted">87 MB · first load</span></div>}{fly.status==='error'&&<div className="brain-overlay error-box"><strong>Couldn’t start the brain</strong><p>{fly.error}</p><button className="control-button" onClick={()=>window.location.reload()}>Retry</button></div>}</div><div className="brain-stats"><div><strong>{fly.tick?num(fly.tick.spikes):'—'}</strong><span>spikes / 20 ms</span></div><div><strong>{fly.tick?num(fly.tick.activeCells):'—'}</strong><span>neurons firing</span></div><div className="retina-wrap"><Retina pixels={fly.retina}/><span>Fly’s view</span></div></div><SignalChart trace={fly.trace}/><div className="session-summary"><span><Heart size={16}/><strong>{fly.runStats.likes}</strong> likes</span><span><X size={16}/><strong>{fly.runStats.passes}</strong> passes</span><span className="model-label">Trained readout</span></div></section></div>
 <History items={fly.history}/>{fly.storageWarning&&<p role="alert" className="storage-warning">History can’t be saved in this browser. Export it before closing.</p>}<footer><span>Frozen model · held-out portraits · illustrative fly motion</span><span>Non-commercial research demo</span></footer></main>;
}
